"""Import Indonesian province and regency emblems for the tax catalogue."""

from pathlib import Path
import json
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "frontend" / "public" / "assets" / "tax-regions"
DATA = ROOT / "frontend" / "src" / "data" / "tax-region-assets.js"
SOURCE = "https://github.com/JastinXyz/indonesia-logo.git"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.iterdir():
        if old.is_file():
            old.unlink()
    with tempfile.TemporaryDirectory(prefix="antarapulsa-tax-") as temp:
        checkout = Path(temp) / "indonesia-logo"
        subprocess.run(["git", "clone", "--depth", "1", SOURCE, str(checkout)], check=True)
        provinces = json.loads((checkout / "data" / "provinces.json").read_text(encoding="utf-8"))
        cities = json.loads((checkout / "data" / "cities.json").read_text(encoding="utf-8"))
        entries = []
        for group, items in (("province", provinces), ("region", cities)):
            for item in items:
                candidates = list((checkout / "images").glob(f'{item["code"]}.*'))
                if not candidates:
                    continue
                source = candidates[0]
                filename = f"{group}-{item['code']}{source.suffix.lower()}"
                shutil.copyfile(source, OUT / filename)
                entries.append((item["name"].title(), f"/assets/tax-regions/{filename}"))
    lines = ["// Generated by tools/import-tax-region-logos.py", "export const taxRegionAssets = {"]
    for name, path in sorted(entries):
        lines.append(f"  {json.dumps(name, ensure_ascii=False)}: {json.dumps(path)},")
    lines.append("};\n")
    DATA.write_text("\n".join(lines), encoding="utf-8")
    print(f"Imported {len(entries)} verified regional emblems into {OUT}")


if __name__ == "__main__":
    main()
